# Site settings
title: Nairitya Khilari
email: nairityakhilari@gmail.com
url: www.nairityak.in
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: nkman

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nairityakhilari
  - title: facebook
    url: https://facebook.com/nairityak
  - title: google-plus
    url: https://google.com/+nairityakhilari
  - title: bitbucket
    url: http://bitbucket.org/nairitya
  - title: github
    url: https://github.com/nkman
  - title: last.fm
    url: http://www.last.fm/user/nk_man
  - title: linkedin
    url: http://in.linkedin.com/pub/nairitya-khilari/85/917/1a0/en

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']